config/routes.rb
Rails.application.routes.draw do

  root 'things#new'

  resources :things

end

app/models/authorship.rb
class Authorship < ActiveRecord::Base
  belongs_to :user
  belongs_to :thing
end

app/models/cache_version.rb
class CacheVersion < ActiveRecord::Base
  def self.for(name)
    where(name: name).first or create(name:name)
  end

  def cache_key
    updated_at
  end

  def expire!
    update_attribute(:updated_at, (updated_at || Time.now) + 1.second)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :thing
  belongs_to :user
end

app/models/thing.rb
class Thing < ActiveRecord::Base

  has_many :comments, -> { order(created_at: :desc) }

  has_many :authorships
  has_many :users, through: :authorships

  scope :latest, -> { all.limit(9).order("id DESC") }

  serialize :image_meta_data
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authorships
  has_many :things, through: :authorships

  serialize :auth_meta_data
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Trailblazer::Operation::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def tyrant
    Tyrant::Session::new(request.env["warden"])
  end
  helper_method :tyrant

  def process_params!(params)
    params.merge!(current_user: tyrant.current_user)
  end
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  respond_to :html

  def index
    @things = Thing.all.page(1).per(2)
  end

  def show
    present Thing::Update
    form Comment::Create
  end

  def new
    form Thing::Create
    @form.prepopulate!
    render_form
  end

  def create
    run Thing::Create do |op|
      return redirect_to op.model
    end

    @form.prepopulate!
    render :new
  end

  def edit
    form Thing::Update

    render action: :new
  end

  def update
    run Thing::Update do |op|
      return redirect_to op.model
    end

    render action: :new
  end

  def create_comment
    present Thing::Update
    run Comment::Create do |op| # overrides @model and @form!
      flash[:notice] = "Created comment for \"#{op.thing.name}\""
      return redirect_to thing_path(op.thing)
    end

    render :show
  end

  def next_comments
    present Thing::Update

    render js:
      concept("comment/cell/grid", @thing, page: params[:page]).(:append)
  end

  private

  def render_form
    Slim::Engine.with_options(disable_escape: true, use_html_safe: true) do
      render text: concept("thing/cell/form", @operation), layout: true
      # render :page, layout: true
    end
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  ### Titre de la page
  def title(page_title = '')
    default_title = "#{ENV['APP_NAME_HUMAN']}"
    if page_title.empty?
      default_title
    else
      "#{page_title} - #{base_title}"
    end
  end

  ### Description de la page
  def description(page_description = '')
    base_description = "Appcustom Description"
    if page_description.empty?
      base_description
    else
      "#{page_description}"
    end
  end
  
  ### Image de la page ou default
  def image(page_image = '')
    default_image = asset_url "/images/main/main.jpg"
    if page_image.empty?
      default_image
    else
      asset_url "#{page_image}"
    end
  end

  ### Flash Message translation
  def alert_class_for(flash_type)
    {
      :success => 'alert-success',
      :error => 'alert-danger',
      :alert => 'alert-warning',
      :notice => 'alert-info'
    } [flash_type.to_sym] || flash_type.to_s
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/comments/new.html.slim
= simple_form_for [@thing, @form] do |f|
  
  = f.error_notification

  = f.input :body
  = f.collection_radio_buttons :weight, *@form.weights, 
                               item_wrapper_class: :radio,
                               item_wrapper_tag: :div

  = f.simple_fields_for :user do |ff|
    = ff.input :email

  = f.button :submit

app/views/home/index.html.slim
h1 Welcome to GemGem

.row
  - things = Thing.latest
  = concept "thing/cell/grid"

app/views/layouts/_header.html.slim
header
  nav[class="navbar navbar-default navbar-fixed-top navbar-custom" role="navigation"]

    .container-fluid

      .navbar-header.page-scroll
        button.navbar-toggle[type="button" data-toggle="collapse" data-target="#navbar"]
          span.icon-bar
          span.icon-bar
          span.icon-bar
        == link_to image_tag("logos/navbar.svg"), root_path, class:"navbar-brand-img svg"

      .collapse.navbar-collapse id="navbar"

app/views/layouts/_messages.html.slim
- flash.each do |type, message|
  .alert.alert-dismissible.fade.in class=(alert_class_for(type))
    a href="#" data-dismiss="alert" class="close" &times;
    .text-center = message

app/views/layouts/_meta.html.slim
/// GENERAL
title
  = title(yield(:title))

meta name="description" content= description(yield(:description))

/// GOOGLE
meta name="itemprop:description" content= description(yield(:description))
meta name="itemprop:name" content="#{ENV['APP_NAME_HUMAN']}"
meta name="itemprop:image" content= image(yield(:image))

/// FACEBOOK
meta property="og:url" content= request.original_url
meta property="og:site_name" content="#{ENV['APP_NAME_HUMAN']}"
meta property="og:see_also" content= "#{request.protocol}#{request.host}"
meta property="og:description" content= description(yield(:description))
meta property="og:title" content= title(yield(:title))
meta property="og:image" content= image(yield(:image))
meta property="og:fb:admins" content="{ENV['FB_ADMINS']}"

/// TWITTER
meta name="twitter:image:src" content= image(yield(:image))
meta name="twitter:domain" content= request.host
meta name="twitter:card" content= description(yield(:description))
meta name="twitter:site" content="#{ENV['TWITTER_ID']}"
meta name="twitter:description" content=description(yield(:description))
meta name="twitter:url" content= request.original_url

app/views/layouts/_shim.html.slim
/[if lt IE 9]
  script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"

app/views/layouts/application.html.slim
doctype html
html
  head
    = render 'layouts/meta'
    
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true

    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = render 'layouts/shim'

  body
  
    = render 'layouts/header'

    = render 'layouts/messages'
    
    .container
      = yield

app/views/pages/home.html.slim
h1 This is the home

h1 This is the home

h1 This is the home

h1 This is the home

h1 This is the home

h1 This is the home

h1 This is the home

h1 This is the home

h1 This is the home

h1 This is the home

h1 This is the home

h1 This is the home

h1 This is the home

h1 This is the home

h1 This is the home

h1 This is the home

h1 This is the home

h1 This is the home

h1 This is the home

h1 This is the home

h1 This is the home

app/views/shared/_error_messages.html.slim.erb
- if object.errors.any?
  div[id="error_explanation"]
    .alert.alert-danger role="alert
      | Ce formulaire contient 
      = pluralize(object.errors.count, "erreur")
      | .
    
    ul
    - object.errors.full_messages.each do |msg|
      li.text-danger.list-unstyled
        i.glyphicon.glyphicon-remove
        = msg

app/views/things/index.html.slim
h1 Things

- if @things.present?
  ul
    - @things.each do |thing|
      li
        strong = thing.name
        span> ,
        small = thing.description
  = paginate @things

- else
  em no things!

app/views/things/new.html.slim
= simple_form_for @form do |f| 
  
  = f.error_notification

  = f.input :name, readonly: @form.readonly?(:name)
  = f.input :description
  = f.input :file, as: :file

  .panel.panel-default
    .panel-heading
      h3 Do you know any authors?
    .panel-body
      = f.fields_for :users do |ff|
        - if @operation.instance_of? Thing::Create
          = ff.input :email
        - else
          = ff.input :email, readonly: ff.object.removeable?
          - if ff.object.removeable?
            = ff.input :remove, as: :boolean, input_html: {checked: false}
  
  = f.submit

app/views/things/show.html.slim
.panel.panel-info
  .panel-heading
    h1
      = concept("thing/cell/decorator", @thing).(:thumb)
      = @thing.name
      small< = link_to "Edit", edit_thing_path(@thing)
  .panel-body
    p = @thing.description
  .panel-footer
    - @thing.users.each do |user|
      span> = user.email


.panel.panel-default
  .panel-body
    = simple_form_for @form, url: create_comment_thing_path(@thing) do |f|
      
      = f.error_notification

      = f.input :body
      = f.collection_radio_buttons :weight, *@form.weights, 
                                   item_wrapper_class: :radio,
                                   item_wrapper_tag: :div

      = f.simple_fields_for :user do |ff|
        = ff.input :email

      = f.button :submit

.panel.panel-default
  .panel-body
    h3 
      span> = @thing.comments.size
      span> comments

    /= concept "comment/cell", collection: @thing.comments.limit(10)
    = concept "comment/cell/grid", @thing